sudo: false
language: node_js
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./bin/score.sh; fi'
