sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
after_success:
  - './bin/success.sh'
